/*
 * overlay_base.h
 *
 *  Created on: Jun 5, 2021
 *      Author: ss2n18
 */

#ifndef INC_OVERLAY_BASE_H_
#define INC_OVERLAY_BASE_H_

#include <stdint.h>

//#define OVERLAY_FW

#define	NUM_DMA_STREAMS_USED			2

#ifdef OVERLAY_FW

typedef struct TinyOpsBuffSizes {

	uint32_t partitionBuff1Size;
	uint32_t partitionBuff2Size;
	uint32_t partitionFilterSize;
	uint32_t partitionIm2colSize;
	uint32_t biasSize;
	uint32_t quantParamsOutShiftSize;
	uint32_t quantParamsOutMultiplierSize;

} TinyOpsBuffSizes;

#define BENCHMARK_TINYOPS_STATS

#define MAX_PARTITION_FACTOR			224

#define PARTITION_FACTOR				MAX_PARTITION_FACTOR
#define TENSOR_BUFFER_SIZE				(49152 + SCRATCH_BUFFER_EXTRA)
#define INPUT2_TENSOR_BUFFER_0_SIZE		(98304 + SCRATCH_BUFFER_EXTRA)
#define INPUT2_TENSOR_BUFFER_1_SIZE		(75264 + SCRATCH_BUFFER_EXTRA)
#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

#define OVERLAY_FILTERS
#define OVERLAY_BIASES
#define OVERLAY_QUANT_PARAMS
//#define OVERLAY_OUTPUT_TENSORS

#define MAX_INTERMEDIATE_BUFF_SIZE		(32000)
#define MAX_RECEPTIVE_FIELD_SIZE		47040
#define MAX_NUM_OPERATIONS				140

#define OP_MAX_INPUT_SIZE				2

#define PRIMARY_PARTITION_DIM			1
#define FIRST_OPERATION_STATE_VAL		0
#define	FIRST_PART_STATE_VAL			0

#define DIM_IDX_BATCH_SIZE				0
#define DIM_IDX_HEIGHT					1
#define DIM_IDX_WIDTH					2
#define DIM_IDX_CHANNELS				3

#define PARTITION_OP_DATA_SIZE			2

#define OP_DATA_CONV_PAD_IDX			0

#define OP_DATA_POOL_PAD_IDX			0

#define OP_DATA_PAD_H_TOP_PAD_IDX		0
#define OP_DATA_PAD_H_BOT_PAD_IDX		1

#define MAX_NUM_DIMS					4

#define MAX_RECEPTIVE_FIELD_LIST_SIZE	5
#define DEPTHWISE_CONV_RC_MULTIPLIER	2
#define CONV_RC_MULTIPLIER				4

#define BATCH_DIMENSION					0
#define ROW_DIMENSION					1

#define SCRATCH_BUFFER_EXTRA			32
#define CONV_SCRATCH_BUFFER_SIZE		(MAX_RECEPTIVE_FIELD_SIZE + SCRATCH_BUFFER_EXTRA)

///////////// TinyOps ///////////////

// proxyless-w0.30-r176
//#define PARTITION_FACTOR				3
//#define TENSOR_BUFFER_SIZE				(73920 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(73920 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(73920 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

///////////// PO-TFLM (No Filter Overlay) ///////////////

// mbv2-w0.3-r80
//#define PARTITION_FACTOR				2
//#define TENSOR_BUFFER_SIZE				(46368 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(46368 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(46368 + SCRATCH_BUFFER_EXTRA)

// mbv2-w0.35-r144
//#define PARTITION_FACTOR				4
//#define TENSOR_BUFFER_SIZE				(74592 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(74592 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(74592 + SCRATCH_BUFFER_EXTRA)

// proxyless-s-w0.25-r112
//#define PARTITION_FACTOR				2
//#define TENSOR_BUFFER_SIZE				(47520 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(47520 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(47520 + SCRATCH_BUFFER_EXTRA)

// proxyless-s-w0.3-r176
//#define PARTITION_FACTOR				4
//#define TENSOR_BUFFER_SIZE				(59616 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(59616 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(59616 + SCRATCH_BUFFER_EXTRA)

// mcunet-320kb-1mb
//#define PARTITION_FACTOR				4
//#define TENSOR_BUFFER_SIZE  			(76000 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(76800 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(76000 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-96
//#define PARTITION_FACTOR				2
//#define TENSOR_BUFFER_SIZE  			(57600 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-128
//#define PARTITION_FACTOR				3
//#define TENSOR_BUFFER_SIZE  			(70656 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(70656 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(70656 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-160
//#define PARTITION_FACTOR				5
//#define TENSOR_BUFFER_SIZE  			(65280 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(65280 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(65280 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-192
//#define PARTITION_FACTOR				7
//#define TENSOR_BUFFER_SIZE  			(69120 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(69120 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(69120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-0.5-224
//#define PARTITION_FACTOR				5
//#define TENSOR_BUFFER_SIZE  			(67200 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(67200 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(67200 + SCRATCH_BUFFER_EXTRA)

// mnasnet-0.75-224
//#define PARTITION_FACTOR				10
//#define TENSOR_BUFFER_SIZE  			(69888 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(69888 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(69888 + SCRATCH_BUFFER_EXTRA)

///////////// PO-TFLM ///////////////

// mbv2-w0.3-r80
//#define PARTITION_FACTOR				2
//#define TENSOR_BUFFER_SIZE				(46368 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(46368 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(46368 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// mbv2-w0.35-r144
//#define PARTITION_FACTOR				4
//#define TENSOR_BUFFER_SIZE				(74592 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(74592 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(74592 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// proxyless-s-w0.25-r112
//#define PARTITION_FACTOR				2
//#define TENSOR_BUFFER_SIZE				(47520 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(47520 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(47520 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// proxyless-s-w0.4-r80
//#define PARTITION_FACTOR				2
//#define TENSOR_BUFFER_SIZE				(47520 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(65536 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(47520 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// proxyless-s-w0.65-r48
//#define PARTITION_FACTOR				2
//#define TENSOR_BUFFER_SIZE				(49152 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(98304 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(75264 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// proxyless-s-w0.3-r176
//#define PARTITION_FACTOR				4
//#define TENSOR_BUFFER_SIZE				(59616 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(59616 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(59616 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// mcunet-320kb-1mb // 310560
//#define PARTITION_FACTOR				4
//#define TENSOR_BUFFER_SIZE  			(76000 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(76800 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(76000 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(1920 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(1920 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-96
//#define PARTITION_FACTOR				2
//#define TENSOR_BUFFER_SIZE  			(57600 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-128 // 297984
//#define PARTITION_FACTOR				3
//#define TENSOR_BUFFER_SIZE  			(70656 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(70656 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(70656 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-128 // 229632
//#define PARTITION_FACTOR				4
//#define TENSOR_BUFFER_SIZE  			(52224 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(52224 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-128 // 211200
//#define PARTITION_FACTOR				5
//#define TENSOR_BUFFER_SIZE  			(46080 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(46080 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-128 // 192768
//#define PARTITION_FACTOR				6
//#define TENSOR_BUFFER_SIZE  			(39936 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(39936 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-128 // 174336
//#define PARTITION_FACTOR				7
//#define TENSOR_BUFFER_SIZE  			(33792 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(33792 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-128 // 169728
//#define PARTITION_FACTOR				8
//#define TENSOR_BUFFER_SIZE  			(32256 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(32256 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-128 // 169728
//#define PARTITION_FACTOR				128
//#define TENSOR_BUFFER_SIZE  			(32256 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(32256 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-160 // 276,480
//#define PARTITION_FACTOR				5
//#define TENSOR_BUFFER_SIZE  			(65280 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(65280 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(65280 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-192 // 291,840
//#define PARTITION_FACTOR				7
//#define TENSOR_BUFFER_SIZE  			(69120 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(69120 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(69120 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-0.5-224
//#define PARTITION_FACTOR				5
//#define TENSOR_BUFFER_SIZE  			(67200 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(92160 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(67200 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-0.75-224
//#define PARTITION_FACTOR				10
//#define TENSOR_BUFFER_SIZE  			(69888 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(69888 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(69888 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// max_part_factor_testing

// mbv2-w0.3-r80 // 36,192
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(6048 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(6048 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(6048 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// mbv2-w0.35-r144 // 56,800
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(11200 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(11200 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(11200 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// proxyless-w0.25-r112 // 100,704
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(20160 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(20160 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(28224 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// proxyless-w0.3-r176 //
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(32256 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(32256 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-96 // 135,168
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(20736 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(20736 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-128 // 169,728
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(32256 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(32256 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-160 // 188,800
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(40320 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(40320 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-192 // 218,112
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(48384 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(48384 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mnasnet-1.0-192 // 218,112
//#define PARTITION_FACTOR				10
//#define TENSOR_BUFFER_SIZE  			(51840 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(51840 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(57600 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mcunet-256kb-1mb // 135,648
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(30912 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(30912 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(30912 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(4000 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(4000 + SCRATCH_BUFFER_EXTRA)

// mcunet-320kb-1mb // 183,360
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(40320 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(40320 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(47040 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// mcunet-512kb-2mb // 204,864
//#define PARTITION_FACTOR				224
//#define TENSOR_BUFFER_SIZE  			(44352 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_0_SIZE		(44352 + SCRATCH_BUFFER_EXTRA)
//#define INPUT2_TENSOR_BUFFER_1_SIZE		(56448 + SCRATCH_BUFFER_EXTRA)
//#define BIAS_TENSOR_BUFFER_SIZE			(5120 + SCRATCH_BUFFER_EXTRA)
//#define QUANT_PARAMS_BUFFER_SIZE		(5120 + SCRATCH_BUFFER_EXTRA)

// (1, 32, 32, 3) => (batch_size, #rows, #columns, #channels)
// partition the rows, cmsis-nn implementation runs through rows, easier this way, also data is stored row-wise
// or more generically always partition in 2nd dimension, which is the rows dimension for image feature map
// or dimensionality in case of vector

#endif

#endif /* INC_OVERLAY_BASE_H_ */
